<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Knowledge"/>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
        <ProjectReference Include="..\Utils\Utils.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MathNet.Numerics" Version="5.0.0"/>
    </ItemGroup>

</Project>
